name: install-and-test-workflow
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r nomad/requirements.txt git+https://github.com/nomad-coe/nomad.git@develop
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
    - name: Test with nomad
      run: |
        python -m nomad.cli parse tests/data/Si_scf/running_scf.log
  build-and-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build the package
      run: |
        pip install --upgrade pip
        pip install build
        python -m build --sdist
    - name: Install the package
      run: |
        pip install dist/*.tar.gz
    - name: Test with nomad
      run: |
        python -m nomad.cli parse tests/data/Si_scf/running_scf.log
